if(EXISTS "/home/runner/work/onnx-light/onnx-light/build-cpp-tests/test_onnx_helper[1]_tests.cmake")
  include("/home/runner/work/onnx-light/onnx-light/build-cpp-tests/test_onnx_helper[1]_tests.cmake")
else()
  add_test(test_onnx_helper_NOT_BUILT test_onnx_helper_NOT_BUILT)
endif()
