"""Generates dependency-free ORT formal-input metadata from registered schemas."""

import argparse
import difflib
import json
from pathlib import Path
import sys

from onnx_light.onnx import defs

SNAPSHOT = (
    Path(__file__).resolve().parents[2]
    / "onnx_light"
    / "onnx_proto"
    / "onnx_ort_input_schemas.inc"
)


def generate_ort_input_schemas() -> str:
    """Returns a deterministic snapshot of every registered input signature.

    Retains the first revision of each consecutive identical signature, including
    its variadic minimum and schema input-count bounds. Rejects layouts that
    cannot use a single trailing variadic minimum instead of silently generating
    incomplete metadata.
    """
    defs.register_onnx_operator_set_schema()
    option = defs.OpSchema.FormalParameterOption
    kinds = {option.Single: "S", option.Optional: "O", option.Variadic: "V"}
    schemas = sorted(
        defs.get_all_schemas_with_history(),
        key=lambda schema: (schema.domain, schema.name, schema.since_version),
    )
    if not schemas:
        raise ValueError("The registered schema history is empty.")
    strings = {}
    pool_size = 0
    records = []
    previous = None
    for schema in schemas:
        inputs = "".join(kinds[param.option] for param in schema.inputs)
        if "V" in inputs and (inputs.count("V") != 1 or not inputs.endswith("V")):
            raise ValueError(
                f"Unsupported variadic layout: {schema.domain!r} "
                f"{schema.name} v{schema.since_version}: {inputs}"
            )
        minimum = schema.inputs[-1].min_arity if inputs.endswith("V") else 0
        for field, value, limit in (
            ("since_version", schema.since_version, 255),
            ("min_variadic_arity", minimum, 255),
            ("min_input", schema.min_input, 255),
            ("max_input", schema.max_input, 2147483647),
        ):
            if not isinstance(value, int) or not 0 <= value <= limit:
                raise ValueError(
                    f"{schema.domain!r} {schema.name} v{schema.since_version}: "
                    f"{field}={value!r} is outside [0, {limit}]."
                )
        if schema.min_input > schema.max_input:
            raise ValueError(f"{schema.name}: min_input exceeds max_input.")
        signature = (
            schema.domain,
            schema.name,
            inputs,
            minimum,
            schema.min_input,
            schema.max_input,
        )
        if signature == previous:
            continue
        previous = signature
        for value in (schema.domain, schema.name, inputs):
            if value in strings:
                continue
            if not value.isascii() or any(not 32 <= ord(char) <= 126 for char in value):
                raise ValueError(f"Schema string must contain printable ASCII: {value!r}")
            # Includes each explicit NUL and the final implicit C++ string NUL.
            if pool_size + len(value) + 2 > 65536:
                raise ValueError("Schema string pool exceeds the uint16_t address space.")
            strings[value] = pool_size
            pool_size += len(value) + 1
        records.append(
            f"    {{{strings[schema.domain]}, {strings[schema.name]}, "
            f"{schema.since_version}, {strings[inputs]}, {minimum}, "
            f"{schema.min_input}, {schema.max_input}}},"
        )
    lines = [
        "// Generated by .github/scripts/generate_ort_input_schemas.py; do not edit.",
        "// Keeps the first revision of consecutive identical input signatures.",
        "// S = Single, O = Optional, V = Variadic (at most one, always trailing).",
        "// min_variadic_arity is zero when there is no variadic parameter.",
        "// min_input/max_input are the registered schema input-count bounds.",
        "// Included inside an anonymous namespace; requires <cstdint>.",
        "",
        "// clang-format off",
        "static constexpr char kOrtInputSchemaStrings[] =",
    ]
    lines.extend(f'    {json.dumps(value)[:-1]}\\0"' for value in strings)
    lines[-1] += ";"
    lines.extend(
        [
            "// clang-format on",
            "",
            "struct OrtInputSchema {",
            "  uint16_t domain;",
            "  uint16_t name;",
            "  uint8_t since_version;",
            "  uint16_t inputs;",
            "  uint8_t min_variadic_arity;",
            "  uint8_t min_input;",
            "  int32_t max_input;",
            "",
            "  const char *Domain() const { return kOrtInputSchemaStrings + domain; }",
            "  const char *Name() const { return kOrtInputSchemaStrings + name; }",
            "  const char *Inputs() const { return kOrtInputSchemaStrings + inputs; }",
            "};",
            'static_assert(sizeof(OrtInputSchema) == 16, "ORT input schema record size");',
            "",
            "static constexpr OrtInputSchema kOrtInputSchemas[] = {",
        ]
    )
    lines.extend(records)
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    """Writes the snapshot or checks its exact byte-for-byte reproducibility."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Checks the committed snapshot without writing."
    )
    args = parser.parse_args()
    generated = generate_ort_input_schemas().encode("utf-8")
    if not args.check:
        SNAPSHOT.write_bytes(generated)
        return 0
    if not SNAPSHOT.is_file():
        print(f"Missing snapshot: {SNAPSHOT}", file=sys.stderr)
        return 1
    committed = SNAPSHOT.read_bytes()
    if committed == generated:
        return 0
    sys.stderr.writelines(
        difflib.unified_diff(
            committed.decode("utf-8").splitlines(keepends=True),
            generated.decode("utf-8").splitlines(keepends=True),
            fromfile=str(SNAPSHOT),
            tofile="regenerated",
        )
    )
    print(
        "Regenerate with: python .github/scripts/generate_ort_input_schemas.py", file=sys.stderr
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
