[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "onnx-light"
version = "0.1.0"
description = "onnx without protobuf"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest>=7",
    "pytest-cov",
    "ruff",
]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312", "py313"]
skip-magic-trailing-comma = true

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501", "I001"]
