if(EXISTS "/home/runner/work/onnx-light/onnx-light/build2/test_onnx_light[1]_tests.cmake")
  include("/home/runner/work/onnx-light/onnx-light/build2/test_onnx_light[1]_tests.cmake")
else()
  add_test(test_onnx_light_NOT_BUILT test_onnx_light_NOT_BUILT)
endif()
