// Copyright (c) ONNX Project Contributors
//
// SPDX-License-Identifier: Apache-2.0

#include "onnx_extensions/kernels/kernel_dispatch_table.h"

#include "onnx_core/runtime/kernel_dispatch_table.h"
#include "onnx_core/runtime/node_helpers.h"
#include "onnx_core/runtime/run_nodes.h"
#include "onnx_core/runtime/simple_tensor.h"
#include "onnx_extensions/kernels/kernels/generator/include_generator_kernels.h"
#include "onnx_extensions/kernels/kernels/image/include_image_kernels.h"
#include "onnx_extensions/kernels/kernels/logical/include_logical_kernels.h"
#include "onnx_extensions/kernels/kernels/math/include_math_kernels.h"
#include "onnx_extensions/kernels/kernels/nn/include_nn_kernels.h"
#include "onnx_extensions/kernels/kernels/object_detection/include_object_detection_kernels.h"
#include "onnx_extensions/kernels/kernels/optional/include_optional_kernels.h"
#include "onnx_extensions/kernels/kernels/preview/include_preview_kernels.h"
#include "onnx_extensions/kernels/kernels/quantization/include_quantization_kernels.h"
#include "onnx_extensions/kernels/kernels/reduction/include_reduction_kernels.h"
#include "onnx_extensions/kernels/kernels/rt/include_rt_kernels.h"
#include "onnx_extensions/kernels/kernels/sequence/include_sequence_kernels.h"
#include "onnx_extensions/kernels/kernels/tensor/include_tensor_kernels.h"
#include "onnx_extensions/kernels/kernels/text/include_text_kernels.h"
#include "onnx_extensions/kernels/kernels/traditionalml/include_traditionalml_kernels.h"
#include "onnx_extensions/kernels/kernels/training/include_training_kernels.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <memory>
#include <optional>
#include <span>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>

namespace ONNX_LIGHT_NAMESPACE::onnx_kernels {

// The generic per-node helpers (``RequireInputCount``, ``GetInput``, ...)
// and runtime types (``Tensor``, ``RuntimeContext``, ...) now live in
// ``onnx_core::runtime`` (see ``onnx_core/runtime/node_helpers.h``); pull
// them in unqualified so the dispatch-table factory below can refer to them
// without qualification. Each kernel's ``KernelBase::Run`` implementation
// lives alongside its ``operator()`` in the kernel's own source file.
using namespace ::onnx_light::core::runtime;

namespace {

// Built-in table of every ``onnx_kernels`` operator kernel, keyed by
// ``"<domain>:<op_type>"``. Only used to populate the shared
// ``core::runtime`` dispatch table via :cpp:func:`RegisterKernelFunctions`;
// never queried directly by :cpp:func:`core::runtime::RunNode`.
// Builds the trivial dispatch factory for a concrete kernel ``KernelT``: it
// constructs the kernel from the node's :cpp:class:`KernelContext`, attaches the
// node it runs for and hands ownership to the runtime, which calls
// :cpp:func:`KernelBase::Run` once per node.
template <class KernelT> NodeKernelFn MakeKernel() {
  return [](const NodeProto &node, RuntimeContext &rt) -> std::unique_ptr<KernelBase> {
    auto kernel = std::make_unique<KernelT>(rt.kernel_ctx());
    kernel->set_node(node);
    return kernel;
  };
}

// A built-in kernel table entry: the factory that constructs the kernel plus
// its explicit unique name (a string literal with static storage; see
// :cpp:class:`core::runtime::KernelBase`).
struct BuiltinKernel {
  const char *name;
  NodeKernelFn fn;
};

const std::unordered_map<std::string, BuiltinKernel> &BuiltinKernelFunctions() {
  static const std::unordered_map<std::string, BuiltinKernel> table = {
      {"ai.rt:DelayedInitializer",
       {"onnx_kernels:CPU:ai.rt:DelayedInitializer",
        MakeKernel<onnx_kernels::kernel::DelayedInitializer>()}},
      {"ai.onnx:Abs", {"onnx_kernels:CPU:ai.onnx:Abs", MakeKernel<onnx_kernels::kernel::Abs>()}},
      {"ai.onnx:Acos", {"onnx_kernels:CPU:ai.onnx:Acos", MakeKernel<onnx_kernels::kernel::Acos>()}},
      {"ai.onnx:Acosh",
       {"onnx_kernels:CPU:ai.onnx:Acosh", MakeKernel<onnx_kernels::kernel::Acosh>()}},
      {"ai.onnx:Add", {"onnx_kernels:CPU:ai.onnx:Add", MakeKernel<onnx_kernels::kernel::Add>()}},
      {"ai.onnx:AffineGrid",
       {"onnx_kernels:CPU:ai.onnx:AffineGrid", MakeKernel<onnx_kernels::kernel::AffineGrid>()}},
      {"ai.onnx:And", {"onnx_kernels:CPU:ai.onnx:And", MakeKernel<onnx_kernels::kernel::And>()}},
      {"ai.onnx:ArgMax",
       {"onnx_kernels:CPU:ai.onnx:ArgMax", MakeKernel<onnx_kernels::kernel::ArgMax>()}},
      {"ai.onnx:ArgMin",
       {"onnx_kernels:CPU:ai.onnx:ArgMin", MakeKernel<onnx_kernels::kernel::ArgMin>()}},
      {"ai.onnx:Asin", {"onnx_kernels:CPU:ai.onnx:Asin", MakeKernel<onnx_kernels::kernel::Asin>()}},
      {"ai.onnx:Asinh",
       {"onnx_kernels:CPU:ai.onnx:Asinh", MakeKernel<onnx_kernels::kernel::Asinh>()}},
      {"ai.onnx:Atan", {"onnx_kernels:CPU:ai.onnx:Atan", MakeKernel<onnx_kernels::kernel::Atan>()}},
      {"ai.onnx:Atanh",
       {"onnx_kernels:CPU:ai.onnx:Atanh", MakeKernel<onnx_kernels::kernel::Atanh>()}},
      {"ai.onnx:Attention",
       {"onnx_kernels:CPU:ai.onnx:Attention", MakeKernel<onnx_kernels::kernel::Attention>()}},
      {"ai.onnx:AveragePool",
       {"onnx_kernels:CPU:ai.onnx:AveragePool", MakeKernel<onnx_kernels::kernel::AveragePool>()}},
      {"ai.onnx:BitShift",
       {"onnx_kernels:CPU:ai.onnx:BitShift", MakeKernel<onnx_kernels::kernel::BitShift>()}},
      {"ai.onnx:BitCast",
       {"onnx_kernels:CPU:ai.onnx:BitCast", MakeKernel<onnx_kernels::kernel::BitCast>()}},
      {"ai.onnx:BitwiseAnd",
       {"onnx_kernels:CPU:ai.onnx:BitwiseAnd", MakeKernel<onnx_kernels::kernel::BitwiseAnd>()}},
      {"ai.onnx:BitwiseNot",
       {"onnx_kernels:CPU:ai.onnx:BitwiseNot", MakeKernel<onnx_kernels::kernel::BitwiseNot>()}},
      {"ai.onnx:BitwiseOr",
       {"onnx_kernels:CPU:ai.onnx:BitwiseOr", MakeKernel<onnx_kernels::kernel::BitwiseOr>()}},
      {"ai.onnx:BitwiseXor",
       {"onnx_kernels:CPU:ai.onnx:BitwiseXor", MakeKernel<onnx_kernels::kernel::BitwiseXor>()}},
      {"ai.onnx:BatchNormalization",
       {"onnx_kernels:CPU:ai.onnx:BatchNormalization",
        MakeKernel<onnx_kernels::kernel::BatchNormalization>()}},
      {"ai.onnx:Bernoulli",
       {"onnx_kernels:CPU:ai.onnx:Bernoulli", MakeKernel<onnx_kernels::kernel::Bernoulli>()}},
      {"ai.onnx:BlackmanWindow",
       {"onnx_kernels:CPU:ai.onnx:BlackmanWindow",
        MakeKernel<onnx_kernels::kernel::BlackmanWindow>()}},
      {"ai.onnx:CausalConvWithState",
       {"onnx_kernels:CPU:ai.onnx:CausalConvWithState",
        MakeKernel<onnx_kernels::kernel::CausalConvWithState>()}},
      {"ai.onnx:Cast", {"onnx_kernels:CPU:ai.onnx:Cast", MakeKernel<onnx_kernels::kernel::Cast>()}},
      {"ai.onnx:CastLike",
       {"onnx_kernels:CPU:ai.onnx:CastLike", MakeKernel<onnx_kernels::kernel::CastLike>()}},
      {"ai.onnx:Ceil", {"onnx_kernels:CPU:ai.onnx:Ceil", MakeKernel<onnx_kernels::kernel::Ceil>()}},
      {"ai.onnx:Celu", {"onnx_kernels:CPU:ai.onnx:Celu", MakeKernel<onnx_kernels::kernel::Celu>()}},
      {"ai.onnx:CenterCropPad",
       {"onnx_kernels:CPU:ai.onnx:CenterCropPad",
        MakeKernel<onnx_kernels::kernel::CenterCropPad>()}},
      {"ai.onnx:Constant",
       {"onnx_kernels:CPU:ai.onnx:Constant", MakeKernel<onnx_kernels::kernel::Constant>()}},
      {"ai.onnx:ConstantOfShape",
       {"onnx_kernels:CPU:ai.onnx:ConstantOfShape",
        MakeKernel<onnx_kernels::kernel::ConstantOfShape>()}},
      {"ai.onnx:Clip", {"onnx_kernels:CPU:ai.onnx:Clip", MakeKernel<onnx_kernels::kernel::Clip>()}},
      {"ai.onnx:Col2Im",
       {"onnx_kernels:CPU:ai.onnx:Col2Im", MakeKernel<onnx_kernels::kernel::Col2Im>()}},
      {"ai.onnx:Compress",
       {"onnx_kernels:CPU:ai.onnx:Compress", MakeKernel<onnx_kernels::kernel::Compress>()}},
      {"ai.onnx:Concat",
       {"onnx_kernels:CPU:ai.onnx:Concat", MakeKernel<onnx_kernels::kernel::Concat>()}},
      {"ai.onnx:Conv", {"onnx_kernels:CPU:ai.onnx:Conv", MakeKernel<onnx_kernels::kernel::Conv>()}},
      {"ai.onnx:ConvInteger",
       {"onnx_kernels:CPU:ai.onnx:ConvInteger", MakeKernel<onnx_kernels::kernel::ConvInteger>()}},
      {"ai.onnx:ConvTranspose",
       {"onnx_kernels:CPU:ai.onnx:ConvTranspose",
        MakeKernel<onnx_kernels::kernel::ConvTranspose>()}},
      {"ai.onnx:Cos", {"onnx_kernels:CPU:ai.onnx:Cos", MakeKernel<onnx_kernels::kernel::Cos>()}},
      {"ai.onnx:Cosh", {"onnx_kernels:CPU:ai.onnx:Cosh", MakeKernel<onnx_kernels::kernel::Cosh>()}},
      {"ai.onnx:CumSum",
       {"onnx_kernels:CPU:ai.onnx:CumSum", MakeKernel<onnx_kernels::kernel::CumSum>()}},
      {"ai.onnx:CumProd",
       {"onnx_kernels:CPU:ai.onnx:CumProd", MakeKernel<onnx_kernels::kernel::CumProd>()}},
      {"ai.onnx:DeformConv",
       {"onnx_kernels:CPU:ai.onnx:DeformConv", MakeKernel<onnx_kernels::kernel::DeformConv>()}},
      {"ai.onnx:Det", {"onnx_kernels:CPU:ai.onnx:Det", MakeKernel<onnx_kernels::kernel::Det>()}},
      {"ai.onnx:DepthToSpace",
       {"onnx_kernels:CPU:ai.onnx:DepthToSpace", MakeKernel<onnx_kernels::kernel::DepthToSpace>()}},
      {"ai.onnx:SpaceToDepth",
       {"onnx_kernels:CPU:ai.onnx:SpaceToDepth", MakeKernel<onnx_kernels::kernel::SpaceToDepth>()}},
      {"ai.onnx:DequantizeLinear",
       {"onnx_kernels:CPU:ai.onnx:DequantizeLinear",
        MakeKernel<onnx_kernels::kernel::DequantizeLinear>()}},
      {"ai.onnx:DFT", {"onnx_kernels:CPU:ai.onnx:DFT", MakeKernel<onnx_kernels::kernel::DFT>()}},
      {"ai.onnx:Div", {"onnx_kernels:CPU:ai.onnx:Div", MakeKernel<onnx_kernels::kernel::Div>()}},
      {"ai.onnx:Dropout",
       {"onnx_kernels:CPU:ai.onnx:Dropout", MakeKernel<onnx_kernels::kernel::Dropout>()}},
      {"ai.onnx:DynamicQuantizeLinear",
       {"onnx_kernels:CPU:ai.onnx:DynamicQuantizeLinear",
        MakeKernel<onnx_kernels::kernel::DynamicQuantizeLinear>()}},
      {"ai.onnx:Einsum",
       {"onnx_kernels:CPU:ai.onnx:Einsum", MakeKernel<onnx_kernels::kernel::Einsum>()}},
      {"ai.onnx:Elu", {"onnx_kernels:CPU:ai.onnx:Elu", MakeKernel<onnx_kernels::kernel::Elu>()}},
      {"ai.onnx:Equal",
       {"onnx_kernels:CPU:ai.onnx:Equal", MakeKernel<onnx_kernels::kernel::Equal>()}},
      {"ai.onnx:Erf", {"onnx_kernels:CPU:ai.onnx:Erf", MakeKernel<onnx_kernels::kernel::Erf>()}},
      {"ai.onnx:Exp", {"onnx_kernels:CPU:ai.onnx:Exp", MakeKernel<onnx_kernels::kernel::Exp>()}},
      {"ai.onnx:Expand",
       {"onnx_kernels:CPU:ai.onnx:Expand", MakeKernel<onnx_kernels::kernel::Expand>()}},
      {"ai.onnx:EyeLike",
       {"onnx_kernels:CPU:ai.onnx:EyeLike", MakeKernel<onnx_kernels::kernel::EyeLike>()}},
      {"ai.onnx:Flatten",
       {"onnx_kernels:CPU:ai.onnx:Flatten", MakeKernel<onnx_kernels::kernel::Flatten>()}},
      {"ai.onnx:Floor",
       {"onnx_kernels:CPU:ai.onnx:Floor", MakeKernel<onnx_kernels::kernel::Floor>()}},
      {"ai.onnx:Gather",
       {"onnx_kernels:CPU:ai.onnx:Gather", MakeKernel<onnx_kernels::kernel::Gather>()}},
      {"ai.onnx:GatherElements",
       {"onnx_kernels:CPU:ai.onnx:GatherElements",
        MakeKernel<onnx_kernels::kernel::GatherElements>()}},
      {"ai.onnx:GatherND",
       {"onnx_kernels:CPU:ai.onnx:GatherND", MakeKernel<onnx_kernels::kernel::GatherND>()}},
      {"ai.onnx:Gelu", {"onnx_kernels:CPU:ai.onnx:Gelu", MakeKernel<onnx_kernels::kernel::Gelu>()}},
      {"ai.onnx:Gemm", {"onnx_kernels:CPU:ai.onnx:Gemm", MakeKernel<onnx_kernels::kernel::Gemm>()}},
      {"ai.onnx:GlobalAveragePool",
       {"onnx_kernels:CPU:ai.onnx:GlobalAveragePool",
        MakeKernel<onnx_kernels::kernel::GlobalAveragePool>()}},
      {"ai.onnx:GlobalLpPool",
       {"onnx_kernels:CPU:ai.onnx:GlobalLpPool", MakeKernel<onnx_kernels::kernel::GlobalLpPool>()}},
      {"ai.onnx:GlobalMaxPool",
       {"onnx_kernels:CPU:ai.onnx:GlobalMaxPool",
        MakeKernel<onnx_kernels::kernel::GlobalMaxPool>()}},
      {"ai.onnx:Greater",
       {"onnx_kernels:CPU:ai.onnx:Greater", MakeKernel<onnx_kernels::kernel::Greater>()}},
      {"ai.onnx:GreaterOrEqual",
       {"onnx_kernels:CPU:ai.onnx:GreaterOrEqual",
        MakeKernel<onnx_kernels::kernel::GreaterOrEqual>()}},
      {"ai.onnx:GridSample",
       {"onnx_kernels:CPU:ai.onnx:GridSample", MakeKernel<onnx_kernels::kernel::GridSample>()}},
      {"ai.onnx:GroupNormalization",
       {"onnx_kernels:CPU:ai.onnx:GroupNormalization",
        MakeKernel<onnx_kernels::kernel::GroupNormalization>()}},
      {"ai.onnx:GRU", {"onnx_kernels:CPU:ai.onnx:GRU", MakeKernel<onnx_kernels::kernel::GRU>()}},
      {"ai.onnx:HardSigmoid",
       {"onnx_kernels:CPU:ai.onnx:HardSigmoid", MakeKernel<onnx_kernels::kernel::HardSigmoid>()}},
      {"ai.onnx:HardSwish",
       {"onnx_kernels:CPU:ai.onnx:HardSwish", MakeKernel<onnx_kernels::kernel::HardSwish>()}},
      {"ai.onnx:Hardmax",
       {"onnx_kernels:CPU:ai.onnx:Hardmax", MakeKernel<onnx_kernels::kernel::Hardmax>()}},
      {"ai.onnx:HammingWindow",
       {"onnx_kernels:CPU:ai.onnx:HammingWindow",
        MakeKernel<onnx_kernels::kernel::HammingWindow>()}},
      {"ai.onnx:HannWindow",
       {"onnx_kernels:CPU:ai.onnx:HannWindow", MakeKernel<onnx_kernels::kernel::HannWindow>()}},
      {"ai.onnx:Identity",
       {"onnx_kernels:CPU:ai.onnx:Identity", MakeKernel<onnx_kernels::kernel::Identity>()}},
      {"ai.onnx:ImageDecoder",
       {"onnx_kernels:CPU:ai.onnx:ImageDecoder", MakeKernel<onnx_kernels::kernel::ImageDecoder>()}},
      {"ai.onnx:InstanceNormalization",
       {"onnx_kernels:CPU:ai.onnx:InstanceNormalization",
        MakeKernel<onnx_kernels::kernel::InstanceNormalization>()}},
      {"ai.onnx:IsInf",
       {"onnx_kernels:CPU:ai.onnx:IsInf", MakeKernel<onnx_kernels::kernel::IsInf>()}},
      {"ai.onnx:IsNaN",
       {"onnx_kernels:CPU:ai.onnx:IsNaN", MakeKernel<onnx_kernels::kernel::IsNaN>()}},
      {"ai.onnx:LayerNormalization",
       {"onnx_kernels:CPU:ai.onnx:LayerNormalization",
        MakeKernel<onnx_kernels::kernel::LayerNormalization>()}},
      {"ai.onnx:LeakyRelu",
       {"onnx_kernels:CPU:ai.onnx:LeakyRelu", MakeKernel<onnx_kernels::kernel::LeakyRelu>()}},
      {"ai.onnx:Less", {"onnx_kernels:CPU:ai.onnx:Less", MakeKernel<onnx_kernels::kernel::Less>()}},
      {"ai.onnx:LessOrEqual",
       {"onnx_kernels:CPU:ai.onnx:LessOrEqual", MakeKernel<onnx_kernels::kernel::LessOrEqual>()}},
      {"ai.onnx:LinearAttention",
       {"onnx_kernels:CPU:ai.onnx:LinearAttention",
        MakeKernel<onnx_kernels::kernel::LinearAttention>()}},
      {"ai.onnx:Log", {"onnx_kernels:CPU:ai.onnx:Log", MakeKernel<onnx_kernels::kernel::Log>()}},
      {"ai.onnx:LogSoftmax",
       {"onnx_kernels:CPU:ai.onnx:LogSoftmax", MakeKernel<onnx_kernels::kernel::LogSoftmax>()}},
      {"ai.onnx:LSTM", {"onnx_kernels:CPU:ai.onnx:LSTM", MakeKernel<onnx_kernels::kernel::LSTM>()}},
      {"ai.onnx:LRN", {"onnx_kernels:CPU:ai.onnx:LRN", MakeKernel<onnx_kernels::kernel::LRN>()}},
      {"ai.onnx:LpNormalization",
       {"onnx_kernels:CPU:ai.onnx:LpNormalization",
        MakeKernel<onnx_kernels::kernel::LpNormalization>()}},
      {"ai.onnx:LpPool",
       {"onnx_kernels:CPU:ai.onnx:LpPool", MakeKernel<onnx_kernels::kernel::LpPool>()}},
      {"ai.onnx:MatMul",
       {"onnx_kernels:CPU:ai.onnx:MatMul", MakeKernel<onnx_kernels::kernel::MatMul>()}},
      {"ai.onnx:MatMulInteger",
       {"onnx_kernels:CPU:ai.onnx:MatMulInteger",
        MakeKernel<onnx_kernels::kernel::MatMulInteger>()}},
      {"ai.onnx:Max", {"onnx_kernels:CPU:ai.onnx:Max", MakeKernel<onnx_kernels::kernel::Max>()}},
      {"ai.onnx:MaxPool",
       {"onnx_kernels:CPU:ai.onnx:MaxPool", MakeKernel<onnx_kernels::kernel::MaxPool>()}},
      {"ai.onnx:MaxRoiPool",
       {"onnx_kernels:CPU:ai.onnx:MaxRoiPool", MakeKernel<onnx_kernels::kernel::MaxRoiPool>()}},
      {"ai.onnx:MaxUnpool",
       {"onnx_kernels:CPU:ai.onnx:MaxUnpool", MakeKernel<onnx_kernels::kernel::MaxUnpool>()}},
      {"ai.onnx:Mean", {"onnx_kernels:CPU:ai.onnx:Mean", MakeKernel<onnx_kernels::kernel::Mean>()}},
      {"ai.onnx:MeanVarianceNormalization",
       {"onnx_kernels:CPU:ai.onnx:MeanVarianceNormalization",
        MakeKernel<onnx_kernels::kernel::MeanVarianceNormalization>()}},
      {"ai.onnx:MelWeightMatrix",
       {"onnx_kernels:CPU:ai.onnx:MelWeightMatrix",
        MakeKernel<onnx_kernels::kernel::MelWeightMatrix>()}},
      {"ai.onnx:Min", {"onnx_kernels:CPU:ai.onnx:Min", MakeKernel<onnx_kernels::kernel::Min>()}},
      {"ai.onnx:Mish", {"onnx_kernels:CPU:ai.onnx:Mish", MakeKernel<onnx_kernels::kernel::Mish>()}},
      {"ai.onnx:Mod", {"onnx_kernels:CPU:ai.onnx:Mod", MakeKernel<onnx_kernels::kernel::Mod>()}},
      {"ai.onnx:Mul", {"onnx_kernels:CPU:ai.onnx:Mul", MakeKernel<onnx_kernels::kernel::Mul>()}},
      {"ai.onnx:Multinomial",
       {"onnx_kernels:CPU:ai.onnx:Multinomial", MakeKernel<onnx_kernels::kernel::Multinomial>()}},
      {"ai.onnx:Neg", {"onnx_kernels:CPU:ai.onnx:Neg", MakeKernel<onnx_kernels::kernel::Neg>()}},
      {"ai.onnx:NegativeLogLikelihoodLoss",
       {"onnx_kernels:CPU:ai.onnx:NegativeLogLikelihoodLoss",
        MakeKernel<onnx_kernels::kernel::NegativeLogLikelihoodLoss>()}},
      {"ai.onnx:NonMaxSuppression",
       {"onnx_kernels:CPU:ai.onnx:NonMaxSuppression",
        MakeKernel<onnx_kernels::kernel::NonMaxSuppression>()}},
      {"ai.onnx:NonZero",
       {"onnx_kernels:CPU:ai.onnx:NonZero", MakeKernel<onnx_kernels::kernel::NonZero>()}},
      {"ai.onnx:Not", {"onnx_kernels:CPU:ai.onnx:Not", MakeKernel<onnx_kernels::kernel::Not>()}},
      {"ai.onnx:OneHot",
       {"onnx_kernels:CPU:ai.onnx:OneHot", MakeKernel<onnx_kernels::kernel::OneHot>()}},
      {"ai.onnx:Or", {"onnx_kernels:CPU:ai.onnx:Or", MakeKernel<onnx_kernels::kernel::Or>()}},
      {"ai.onnx:Optional",
       {"onnx_kernels:CPU:ai.onnx:Optional", MakeKernel<onnx_kernels::kernel::Optional>()}},
      {"ai.onnx:OptionalGetElement",
       {"onnx_kernels:CPU:ai.onnx:OptionalGetElement",
        MakeKernel<onnx_kernels::kernel::OptionalGetElement>()}},
      {"ai.onnx:OptionalHasElement",
       {"onnx_kernels:CPU:ai.onnx:OptionalHasElement",
        MakeKernel<onnx_kernels::kernel::OptionalHasElement>()}},
      {"ai.onnx:Pad", {"onnx_kernels:CPU:ai.onnx:Pad", MakeKernel<onnx_kernels::kernel::Pad>()}},
      {"ai.onnx:Pow", {"onnx_kernels:CPU:ai.onnx:Pow", MakeKernel<onnx_kernels::kernel::Pow>()}},
      {"ai.onnx:PRelu",
       {"onnx_kernels:CPU:ai.onnx:PRelu", MakeKernel<onnx_kernels::kernel::PRelu>()}},
      {"ai.onnx:QLinearConv",
       {"onnx_kernels:CPU:ai.onnx:QLinearConv", MakeKernel<onnx_kernels::kernel::QLinearConv>()}},
      {"ai.onnx:QLinearMatMul",
       {"onnx_kernels:CPU:ai.onnx:QLinearMatMul",
        MakeKernel<onnx_kernels::kernel::QLinearMatMul>()}},
      {"ai.onnx:QuantizeLinear",
       {"onnx_kernels:CPU:ai.onnx:QuantizeLinear",
        MakeKernel<onnx_kernels::kernel::QuantizeLinear>()}},
      {"ai.onnx:RandomNormal",
       {"onnx_kernels:CPU:ai.onnx:RandomNormal", MakeKernel<onnx_kernels::kernel::RandomNormal>()}},
      {"ai.onnx:RandomNormalLike",
       {"onnx_kernels:CPU:ai.onnx:RandomNormalLike",
        MakeKernel<onnx_kernels::kernel::RandomNormalLike>()}},
      {"ai.onnx:RandomUniform",
       {"onnx_kernels:CPU:ai.onnx:RandomUniform",
        MakeKernel<onnx_kernels::kernel::RandomUniform>()}},
      {"ai.onnx:RandomUniformLike",
       {"onnx_kernels:CPU:ai.onnx:RandomUniformLike",
        MakeKernel<onnx_kernels::kernel::RandomUniformLike>()}},
      {"ai.onnx:Range",
       {"onnx_kernels:CPU:ai.onnx:Range", MakeKernel<onnx_kernels::kernel::Range>()}},
      {"ai.onnx:RMSNormalization",
       {"onnx_kernels:CPU:ai.onnx:RMSNormalization",
        MakeKernel<onnx_kernels::kernel::RMSNormalization>()}},
      {"ai.onnx:Reciprocal",
       {"onnx_kernels:CPU:ai.onnx:Reciprocal", MakeKernel<onnx_kernels::kernel::Reciprocal>()}},
      {"ai.onnx:ReduceL1",
       {"onnx_kernels:CPU:ai.onnx:ReduceL1", MakeKernel<onnx_kernels::kernel::ReduceL1>()}},
      {"ai.onnx:ReduceL2",
       {"onnx_kernels:CPU:ai.onnx:ReduceL2", MakeKernel<onnx_kernels::kernel::ReduceL2>()}},
      {"ai.onnx:ReduceLogSum",
       {"onnx_kernels:CPU:ai.onnx:ReduceLogSum", MakeKernel<onnx_kernels::kernel::ReduceLogSum>()}},
      {"ai.onnx:ReduceLogSumExp",
       {"onnx_kernels:CPU:ai.onnx:ReduceLogSumExp",
        MakeKernel<onnx_kernels::kernel::ReduceLogSumExp>()}},
      {"ai.onnx:ReduceMax",
       {"onnx_kernels:CPU:ai.onnx:ReduceMax", MakeKernel<onnx_kernels::kernel::ReduceMax>()}},
      {"ai.onnx:ReduceMean",
       {"onnx_kernels:CPU:ai.onnx:ReduceMean", MakeKernel<onnx_kernels::kernel::ReduceMean>()}},
      {"ai.onnx:ReduceMin",
       {"onnx_kernels:CPU:ai.onnx:ReduceMin", MakeKernel<onnx_kernels::kernel::ReduceMin>()}},
      {"ai.onnx:ReduceProd",
       {"onnx_kernels:CPU:ai.onnx:ReduceProd", MakeKernel<onnx_kernels::kernel::ReduceProd>()}},
      {"ai.onnx:ReduceSum",
       {"onnx_kernels:CPU:ai.onnx:ReduceSum", MakeKernel<onnx_kernels::kernel::ReduceSum>()}},
      {"ai.onnx:ReduceSumSquare",
       {"onnx_kernels:CPU:ai.onnx:ReduceSumSquare",
        MakeKernel<onnx_kernels::kernel::ReduceSumSquare>()}},
      {"ai.onnx:RegexFullMatch",
       {"onnx_kernels:CPU:ai.onnx:RegexFullMatch",
        MakeKernel<onnx_kernels::kernel::RegexFullMatch>()}},
      {"ai.onnx:Relu", {"onnx_kernels:CPU:ai.onnx:Relu", MakeKernel<onnx_kernels::kernel::Relu>()}},
      {"ai.onnx:Reshape",
       {"onnx_kernels:CPU:ai.onnx:Reshape", MakeKernel<onnx_kernels::kernel::Reshape>()}},
      {"ai.onnx:Resize",
       {"onnx_kernels:CPU:ai.onnx:Resize", MakeKernel<onnx_kernels::kernel::Resize>()}},
      {"ai.onnx:ReverseSequence",
       {"onnx_kernels:CPU:ai.onnx:ReverseSequence",
        MakeKernel<onnx_kernels::kernel::ReverseSequence>()}},
      {"ai.onnx:RoiAlign",
       {"onnx_kernels:CPU:ai.onnx:RoiAlign", MakeKernel<onnx_kernels::kernel::RoiAlign>()}},
      {"ai.onnx:Round",
       {"onnx_kernels:CPU:ai.onnx:Round", MakeKernel<onnx_kernels::kernel::Round>()}},
      {"ai.onnx:RNN", {"onnx_kernels:CPU:ai.onnx:RNN", MakeKernel<onnx_kernels::kernel::RNN>()}},
      {"ai.onnx:RotaryEmbedding",
       {"onnx_kernels:CPU:ai.onnx:RotaryEmbedding",
        MakeKernel<onnx_kernels::kernel::RotaryEmbedding>()}},
      {"ai.onnx:Scatter",
       {"onnx_kernels:CPU:ai.onnx:Scatter", MakeKernel<onnx_kernels::kernel::Scatter>()}},
      {"ai.onnx:ScatterElements",
       {"onnx_kernels:CPU:ai.onnx:ScatterElements",
        MakeKernel<onnx_kernels::kernel::ScatterElements>()}},
      {"ai.onnx:ScatterND",
       {"onnx_kernels:CPU:ai.onnx:ScatterND", MakeKernel<onnx_kernels::kernel::ScatterND>()}},
      {"ai.onnx:Selu", {"onnx_kernels:CPU:ai.onnx:Selu", MakeKernel<onnx_kernels::kernel::Selu>()}},
      {"ai.onnx:ConcatFromSequence",
       {"onnx_kernels:CPU:ai.onnx:ConcatFromSequence",
        MakeKernel<onnx_kernels::kernel::ConcatFromSequence>()}},
      {"ai.onnx:SequenceAt",
       {"onnx_kernels:CPU:ai.onnx:SequenceAt", MakeKernel<onnx_kernels::kernel::SequenceAt>()}},
      {"ai.onnx:SequenceConstruct",
       {"onnx_kernels:CPU:ai.onnx:SequenceConstruct",
        MakeKernel<onnx_kernels::kernel::SequenceConstruct>()}},
      {"ai.onnx:SequenceEmpty",
       {"onnx_kernels:CPU:ai.onnx:SequenceEmpty",
        MakeKernel<onnx_kernels::kernel::SequenceEmpty>()}},
      {"ai.onnx:SequenceErase",
       {"onnx_kernels:CPU:ai.onnx:SequenceErase",
        MakeKernel<onnx_kernels::kernel::SequenceErase>()}},
      {"ai.onnx:SequenceInsert",
       {"onnx_kernels:CPU:ai.onnx:SequenceInsert",
        MakeKernel<onnx_kernels::kernel::SequenceInsert>()}},
      {"ai.onnx:SequenceLength",
       {"onnx_kernels:CPU:ai.onnx:SequenceLength",
        MakeKernel<onnx_kernels::kernel::SequenceLength>()}},
      {"ai.onnx:Split",
       {"onnx_kernels:CPU:ai.onnx:Split", MakeKernel<onnx_kernels::kernel::Split>()}},
      {"ai.onnx:SplitToSequence",
       {"onnx_kernels:CPU:ai.onnx:SplitToSequence",
        MakeKernel<onnx_kernels::kernel::SplitToSequence>()}},
      {"ai.onnx:Shape",
       {"onnx_kernels:CPU:ai.onnx:Shape", MakeKernel<onnx_kernels::kernel::Shape>()}},
      {"ai.onnx:Shrink",
       {"onnx_kernels:CPU:ai.onnx:Shrink", MakeKernel<onnx_kernels::kernel::Shrink>()}},
      {"ai.onnx:Sigmoid",
       {"onnx_kernels:CPU:ai.onnx:Sigmoid", MakeKernel<onnx_kernels::kernel::Sigmoid>()}},
      {"ai.onnx:Sign", {"onnx_kernels:CPU:ai.onnx:Sign", MakeKernel<onnx_kernels::kernel::Sign>()}},
      {"ai.onnx:Sin", {"onnx_kernels:CPU:ai.onnx:Sin", MakeKernel<onnx_kernels::kernel::Sin>()}},
      {"ai.onnx:Sinh", {"onnx_kernels:CPU:ai.onnx:Sinh", MakeKernel<onnx_kernels::kernel::Sinh>()}},
      {"ai.onnx:Size", {"onnx_kernels:CPU:ai.onnx:Size", MakeKernel<onnx_kernels::kernel::Size>()}},
      {"ai.onnx:Slice",
       {"onnx_kernels:CPU:ai.onnx:Slice", MakeKernel<onnx_kernels::kernel::Slice>()}},
      {"ai.onnx:Softmax",
       {"onnx_kernels:CPU:ai.onnx:Softmax", MakeKernel<onnx_kernels::kernel::Softmax>()}},
      {"ai.onnx:SoftmaxCrossEntropyLoss",
       {"onnx_kernels:CPU:ai.onnx:SoftmaxCrossEntropyLoss",
        MakeKernel<onnx_kernels::kernel::SoftmaxCrossEntropyLoss>()}},
      {"ai.onnx:Softplus",
       {"onnx_kernels:CPU:ai.onnx:Softplus", MakeKernel<onnx_kernels::kernel::Softplus>()}},
      {"ai.onnx:Softsign",
       {"onnx_kernels:CPU:ai.onnx:Softsign", MakeKernel<onnx_kernels::kernel::Softsign>()}},
      {"ai.onnx:Sqrt", {"onnx_kernels:CPU:ai.onnx:Sqrt", MakeKernel<onnx_kernels::kernel::Sqrt>()}},
      {"ai.onnx:Squeeze",
       {"onnx_kernels:CPU:ai.onnx:Squeeze", MakeKernel<onnx_kernels::kernel::Squeeze>()}},
      {"ai.onnx:STFT", {"onnx_kernels:CPU:ai.onnx:STFT", MakeKernel<onnx_kernels::kernel::STFT>()}},
      {"ai.onnx:StringConcat",
       {"onnx_kernels:CPU:ai.onnx:StringConcat", MakeKernel<onnx_kernels::kernel::StringConcat>()}},
      {"ai.onnx:StringNormalizer",
       {"onnx_kernels:CPU:ai.onnx:StringNormalizer",
        MakeKernel<onnx_kernels::kernel::StringNormalizer>()}},
      {"ai.onnx:StringSplit",
       {"onnx_kernels:CPU:ai.onnx:StringSplit", MakeKernel<onnx_kernels::kernel::StringSplit>()}},
      {"ai.onnx:Sub", {"onnx_kernels:CPU:ai.onnx:Sub", MakeKernel<onnx_kernels::kernel::Sub>()}},
      {"ai.onnx:Sum", {"onnx_kernels:CPU:ai.onnx:Sum", MakeKernel<onnx_kernels::kernel::Sum>()}},
      {"ai.onnx:Swish",
       {"onnx_kernels:CPU:ai.onnx:Swish", MakeKernel<onnx_kernels::kernel::Swish>()}},
      {"ai.onnx:SwiGLU",
       {"onnx_kernels:CPU:ai.onnx:SwiGLU", MakeKernel<onnx_kernels::kernel::SwiGLU>()}},
      {"ai.onnx:Tan", {"onnx_kernels:CPU:ai.onnx:Tan", MakeKernel<onnx_kernels::kernel::Tan>()}},
      {"ai.onnx:Tanh", {"onnx_kernels:CPU:ai.onnx:Tanh", MakeKernel<onnx_kernels::kernel::Tanh>()}},
      {"ai.onnx:TensorScatter",
       {"onnx_kernels:CPU:ai.onnx:TensorScatter",
        MakeKernel<onnx_kernels::kernel::TensorScatter>()}},
      {"ai.onnx:TfIdfVectorizer",
       {"onnx_kernels:CPU:ai.onnx:TfIdfVectorizer",
        MakeKernel<onnx_kernels::kernel::TfIdfVectorizer>()}},
      {"ai.onnx:ThresholdedRelu",
       {"onnx_kernels:CPU:ai.onnx:ThresholdedRelu",
        MakeKernel<onnx_kernels::kernel::ThresholdedRelu>()}},
      {"ai.onnx:Tile", {"onnx_kernels:CPU:ai.onnx:Tile", MakeKernel<onnx_kernels::kernel::Tile>()}},
      {"ai.onnx:TopK", {"onnx_kernels:CPU:ai.onnx:TopK", MakeKernel<onnx_kernels::kernel::TopK>()}},
      {"ai.onnx:Transpose",
       {"onnx_kernels:CPU:ai.onnx:Transpose", MakeKernel<onnx_kernels::kernel::Transpose>()}},
      {"ai.onnx:Trilu",
       {"onnx_kernels:CPU:ai.onnx:Trilu", MakeKernel<onnx_kernels::kernel::Trilu>()}},
      {"ai.onnx:Unique",
       {"onnx_kernels:CPU:ai.onnx:Unique", MakeKernel<onnx_kernels::kernel::Unique>()}},
      {"ai.onnx:Unsqueeze",
       {"onnx_kernels:CPU:ai.onnx:Unsqueeze", MakeKernel<onnx_kernels::kernel::Unsqueeze>()}},
      {"ai.onnx:Upsample",
       {"onnx_kernels:CPU:ai.onnx:Upsample", MakeKernel<onnx_kernels::kernel::Upsample>()}},
      {"ai.onnx:Where",
       {"onnx_kernels:CPU:ai.onnx:Where", MakeKernel<onnx_kernels::kernel::Where>()}},
      {"ai.onnx:Xor", {"onnx_kernels:CPU:ai.onnx:Xor", MakeKernel<onnx_kernels::kernel::Xor>()}},
      {"ai.onnx.preview:FlexAttention",
       {"onnx_kernels:CPU:ai.onnx.preview:FlexAttention",
        MakeKernel<onnx_kernels::kernel::FlexAttention>()}},
      {"ai.onnx.preview.training:Adagrad",
       {"onnx_kernels:CPU:ai.onnx.preview.training:Adagrad",
        MakeKernel<onnx_kernels::kernel::Adagrad>()}},
      {"ai.onnx.preview.training:Adam",
       {"onnx_kernels:CPU:ai.onnx.preview.training:Adam",
        MakeKernel<onnx_kernels::kernel::Adam>()}},
      {"ai.onnx.preview.training:Momentum",
       {"onnx_kernels:CPU:ai.onnx.preview.training:Momentum",
        MakeKernel<onnx_kernels::kernel::Momentum>()}},
      {"ai.onnx.ml:CastMap",
       {"onnx_kernels:CPU:ai.onnx.ml:CastMap", MakeKernel<onnx_kernels::kernel::CastMap>()}},
      {"ai.onnx.ml:DictVectorizer",
       {"onnx_kernels:CPU:ai.onnx.ml:DictVectorizer",
        MakeKernel<onnx_kernels::kernel::DictVectorizer>()}},
      {"ai.onnx.ml:SVMRegressor",
       {"onnx_kernels:CPU:ai.onnx.ml:SVMRegressor",
        MakeKernel<onnx_kernels::kernel::SVMRegressor>()}},
      {"ai.onnx.ml:SVMClassifier",
       {"onnx_kernels:CPU:ai.onnx.ml:SVMClassifier",
        MakeKernel<onnx_kernels::kernel::SVMClassifier>()}},
      {"ai.onnx.ml:LinearRegressor",
       {"onnx_kernels:CPU:ai.onnx.ml:LinearRegressor",
        MakeKernel<onnx_kernels::kernel::LinearRegressor>()}},
      {"ai.onnx.ml:TreeEnsembleRegressor",
       {"onnx_kernels:CPU:ai.onnx.ml:TreeEnsembleRegressor",
        MakeKernel<onnx_kernels::kernel::TreeEnsembleRegressor>()}},
      {"ai.onnx.ml:LinearClassifier",
       {"onnx_kernels:CPU:ai.onnx.ml:LinearClassifier",
        MakeKernel<onnx_kernels::kernel::LinearClassifier>()}},
      {"ai.onnx.ml:TreeEnsembleClassifier",
       {"onnx_kernels:CPU:ai.onnx.ml:TreeEnsembleClassifier",
        MakeKernel<onnx_kernels::kernel::TreeEnsembleClassifier>()}},
      {"ai.onnx.ml:Binarizer",
       {"onnx_kernels:CPU:ai.onnx.ml:Binarizer", MakeKernel<onnx_kernels::kernel::Binarizer>()}},
      {"ai.onnx.ml:Normalizer",
       {"onnx_kernels:CPU:ai.onnx.ml:Normalizer", MakeKernel<onnx_kernels::kernel::Normalizer>()}},
      {"ai.onnx.ml:Scaler",
       {"onnx_kernels:CPU:ai.onnx.ml:Scaler", MakeKernel<onnx_kernels::kernel::Scaler>()}},
      {"ai.onnx.ml:ArrayFeatureExtractor",
       {"onnx_kernels:CPU:ai.onnx.ml:ArrayFeatureExtractor",
        MakeKernel<onnx_kernels::kernel::ArrayFeatureExtractor>()}},
      {"ai.onnx.ml:Imputer",
       {"onnx_kernels:CPU:ai.onnx.ml:Imputer", MakeKernel<onnx_kernels::kernel::Imputer>()}},
      {"ai.onnx.ml:CategoryMapper",
       {"onnx_kernels:CPU:ai.onnx.ml:CategoryMapper",
        MakeKernel<onnx_kernels::kernel::CategoryMapper>()}},
      {"ai.onnx.ml:LabelEncoder",
       {"onnx_kernels:CPU:ai.onnx.ml:LabelEncoder",
        MakeKernel<onnx_kernels::kernel::LabelEncoder>()}},
      {"ai.onnx.ml:OneHotEncoder",
       {"onnx_kernels:CPU:ai.onnx.ml:OneHotEncoder",
        MakeKernel<onnx_kernels::kernel::OneHotEncoder>()}},
      {"ai.onnx.ml:FeatureVectorizer",
       {"onnx_kernels:CPU:ai.onnx.ml:FeatureVectorizer",
        MakeKernel<onnx_kernels::kernel::FeatureVectorizer>()}},
      {"ai.onnx.ml:TreeEnsemble",
       {"onnx_kernels:CPU:ai.onnx.ml:TreeEnsemble",
        MakeKernel<onnx_kernels::kernel::TreeEnsemble>()}},
  };
  return table;
}

} // namespace

void RegisterKernelFunctions() {
  // `lib_onnx_kernels` is a plain static archive: a translation unit with no
  // symbol referenced from elsewhere would simply be dropped by the linker,
  // so registration cannot rely on a file-scope static object running as a
  // side effect of "just being linked in" (unlike, say,
  // `OpSchemaRegistry::map()` in `onnx_lib`, which can call its registration
  // functions lazily because both live in the same library). Callers must
  // invoke this function explicitly before running a model; it is
  // idempotent, so calling it more than once (or from multiple independent
  // entry points) is safe and cheap after the first call.
  static const bool kRegistered = [] {
    for (const auto &entry : BuiltinKernelFunctions()) {
      const std::string &key = entry.first;
      const std::size_t sep = key.find(':');
      const std::string domain = key.substr(0, sep);
      const std::string op_type = key.substr(sep + 1);
      ::onnx_light::core::runtime::RegisterKernelFn(domain, op_type,
                                                    ::onnx_light::core::symbolic::Device::kCPU,
                                                    entry.second.fn, entry.second.name);
    }
    ::onnx_light::core::runtime::RegisterSequenceMapPackFn(
        [](RuntimeContext &rt, const Sequence &input_sequence,
           const std::vector<Tensors> &body_outputs_per_iter) {
          onnx_kernels::kernel::SequenceMap seq_map_kernel(rt.kernel_ctx());
          return seq_map_kernel(input_sequence, body_outputs_per_iter);
        });
    return true;
  }();
  (void)kRegistered;
}

} // namespace ONNX_LIGHT_NAMESPACE::onnx_kernels
