name: Build Release Wheels

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels_linux:
    name: wheels (linux, ${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp313t-* cp314-* cp314t-*"
          CIBW_ARCHS: ${{ matrix.arch }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build_wheels_windows:
    name: wheels (windows, ${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: AMD64
            runs-on: windows-latest
          - arch: x86
            runs-on: windows-latest
          - arch: ARM64
            runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp313t-* cp314-* cp314t-*"
          CIBW_ARCHS: ${{ matrix.arch }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build_wheels_macos:
    name: wheels (macos, ${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            runs-on: macos-latest
          - arch: x86_64
            runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp313t-* cp314-* cp314t-*"
          CIBW_ARCHS: ${{ matrix.arch }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
