name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build
        run: pip install build
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ubuntu-latest-py3.12
      - name: Build package
        env:
          SKBUILD_CMAKE_ARGS: "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache"
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
