name: clang-format

on:
  workflow_call:
  workflow_dispatch:

jobs:
  clang_format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check C++ formatting
        run: |
          find . \( -name "*.cc" -o -name "*.h" -o -name "*.hpp" \) \
            | grep -v ".git" \
            | xargs clang-format --dry-run --Werror
