name: Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "**.md"
      - "**.rst"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "**.md"
      - "**.rst"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CMAKE_BUILD_PARALLEL_LEVEL: "4"

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      UNITTEST_GOING: "1"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      - name: Install dependencies
        run: pip install -e ".[docs]"
      - name: Install ONNX weekly
        run: pip install --upgrade onnx-weekly
      - name: pip freeze
        run: pip freeze
      - name: Build documentation
        run: |
          sphinx-build -b html docs dist/html -W
